[build]
    publish = "public/"
    command = "gatsby build"
    node_version = "18.18.0"

[build.environment]
    NPM_FLAGS = "--legacy-peer-deps"
    NODE_VERSION = "18.18.0"

[build.processing]
    skip_processing = true