[build]
    publish = "public/"
    command = "npm install --no-optional && gatsby build"
    node_version = "18.18.0"

[build.environment]
    NPM_FLAGS = "--legacy-peer-deps --no-optional"
    NODE_VERSION = "18.18.0"
    NPM_CONFIG_OPTIONAL = "false"
    GATSBY_CPU_COUNT = "2"

[build.processing]
    skip_processing = true